 #!/bin/bash
 mkdir ~/Desktop/yara-rules
 cd ~/Desktop/yara-rules/
 git clone "https://github.com/bartblaze/Yara-rules.git"
 git clone "https://github.com/codewatchorg/Burp-Yara-Rules.git"
 git clone "https://github.com/CyberDefenses/CDI_yara.git"
 git clone "https://github.com/citizenlab/malware-signatures.git"
 git clone "https://github.com/stvemillertime/ConventionEngine.git"
 git clone "https://github.com/deadbits/yara-rules.git"
 #git clone "https://github.com/DidierStevens/DidierStevensSuite.git"
 git clone "https://github.com/eset/malware-ioc.git"
 git clone "https://github.com/mandiant/red_team_tool_countermeasures.git"
 git clone "https://github.com/f0wl/yara_rules.git"
 git clone "https://github.com/fboldewin/YARA-rules.git"
 git clone "https://github.com/godaddy/yara-rules.git GoDaddy"
 git clone "https://github.com/h3x2b/yara-rules.git h3x2b"
 git clone "https://github.com/SupportIntelligence/Icewater.git"
 git clone "https://github.com/imp0rtp3/yara-rules.git imp0rtp3"
 git clone "https://github.com/intezer/yara-rules.git Intezer"
 git clone "https://github.com/InQuest/yara-rules.git InQuest"
 git clone "https://github.com/jeFF0Falltrades/YARA-Signatures.git jeFF0Falltrades"
 git clone "https://github.com/kevthehermit/YaraRules.git kevthehermit"
 git clone "https://github.com/Hestat/lw-yara.git"
 git clone "https://github.com/malpedia/signator-rules.git"
 git clone "https://github.com/advanced-threat-research/IOCs.git"
 git clone "https://github.com/advanced-threat-research/Yara-Rules.git advanced-threat-research"
 #git clone "https://github.com/mikesxrs/Open-Source-YARA-rules.git"
 wget "https://malpedia.caad.fkie.fraunhofer.de/api/get/yara/auto/zip"
 mkdir malpedia_auto && unzip zip -d malpedia_auto
 git clone "https://github.com/prolsen/yara-rules.git prolsen"
 git clone "https://github.com/tylabs/qs_old.git"
 git clone "https://github.com/rastrea2r/rastrea2r.git"
 git clone "https://github.com/reversinglabs/reversinglabs-yara-rules.git"
 git clone "https://github.com/securitymagic/yara.git"
 git clone "https://github.com/securitymagic/yara.git securitymagic"
 git clone "https://github.com/sophos-ai/yaraml_rules.git"
 git clone "https://github.com/StrangerealIntel/DailyIOC.git"
 git clone "https://github.com/t4d/PhishingKit-Yara-Rules.git"
 git clone "https://github.com/telekom-security/malware_analysis.git"
 git clone "https://github.com/tenable/yara-rules.git tenable"
 git clone "https://github.com/tjnel/yara_repo.git"
 git clone "https://github.com/VectraThreatLab/reyara.git"
 git clone "https://github.com/volexity/threat-intel.git"
 git clone "https://github.com/x64dbg/yarasigs.git"
 git clone "https://github.com/wrayjustin/yaids.git"
 git clone "https://github.com/Xumeiquer/yara-forensics.git"
 git clone "https://github.com/DiabloHorn/yara4pentesters.git"
 git clone "https://github.com/Yara-Rules/rules.git OfficialYara-Rules"
 git clone "https://github.com/fr0gger/Yara-Unprotect.git"
